### PR TITLE
Revert "Use the main transformers library, rename LLaMA to Llama"

### PR DESCRIPTION
**Pull request by qwopqwop200**
Reverts qwopqwop200/GPTQ-for-LLaMa#52

### CODE REVIEW

**Comment by qwopqwop200** [comment]
I've confirmed that it doesn't work now.

**Comment by sgsdxzy** [comment]
It seems to work for me, at least quantization and quantized model loading work.

**Comment by JustinPack** [comment]
It does not work for the latest instructions. I kept getting the cannot import error until I made the changes reflected in the files changed tab and then reran the requirements install.

Worked perfectly afterwards.

**Comment by qwopqwop200** [comment]
I made some fixes to make all the code work.

**Pull request closed without merging**
