### PR TITLE
Add `.safetensors` support

### PR DESCRIPTION
**Pull request by 81300**

### CODE REVIEW

**Comment by qwopqwop200** [comment]
Currently testing. If it works, I'll merge it.

**Comment by thulle** [comment]
Tested on windows? Seems to break things in linux here:

```
$ python server.py --model llama-13B-4b --load-in-4bit
Loading llama-13B-4b...
Loading model ...
Traceback (most recent call last):
  File "/home/textui/text-generation-webui/server.py", line 191, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/textui/text-generation-webui/modules/models.py", line 119, in load_model
    model = load_quant(path_to_model, Path(f"models/{pt_model}"), 4)
  File "/home/textui/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 241, in load_quant
    if checkpoint.endswith('.safetensors'):
AttributeError: 'PosixPath' object has no attribute 'endswith'
```

**Comment by qwopqwop200** [comment]
Tested on Windows. I'll test it on wsl tomorrow.

**Comment by thulle** [comment]
```
diff --git a/llama.py b/llama.py
index 09b527e..cc652dd 100644
--- a/llama.py
+++ b/llama.py
@@ -238,7 +238,7 @@ def load_quant(model, checkpoint, wbits):
     make_quant(model, layers, wbits)
 
     print('Loading model ...')
-    if checkpoint.endswith('.safetensors'):
+    if checkpoint.as_posix().endswith('.safetensors'):
         from safetensors.torch import load_file as safe_load
         model.load_state_dict(safe_load(checkpoint))
     else:
```

as_posix() returns a string which made it work here

**Pull request merged**
