### PR TITLE
Fix multigpu inference.

### LINKED ISSUE #135: Does triton branch support using multiple gpus?
I can get smaller triton quantized models to run, but the Llama-65b model cannot fit into a single gpu.
I used to get the cuda version to load on multiple gpus, it works almost transparently. However for the triton branch, the models loads, but at inference stage it fails with `expecting tensors on the same device, found 'cuda:0' and 'cuda:1'`
So does the triton branch not support multiple gpu, or needs special treatment?

### PR DESCRIPTION
**Pull request by sgsdxzy**
Currently the triton multigpu is not working:
1. I find the output of `QuantLinear` is always on `cuda:0`. The edits to `quant.py` should fix this by placing the output on the same device as the input.
2. `MoveModule` is not moving keyword arguments to device. This should be fixed now.
3. The attention mask caching is not working correctly as in subsequent generations it is not invalidated, resulting in `model.generate()` only generate 1 token (tested on 1 gpu). I disabled the caching for the time being. Might be able to invalidate the caching before each `forward` in the following modified `forward` but it could introduce other bugs.
4. `model.forward()` should be working now but not `model.generate()`, as `generate()` needs to gather logits and scores back to the same gpu. I gather them in the modified `forward` to `cuda:0`.
5. Then it reports
```
Traceback (most recent call last):
  File "/home/sgsdxzy/Programs/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/sgsdxzy/Programs/text-generation-webui/modules/text_generation.py", line 245, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/sgsdxzy/mambaforge/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sgsdxzy/mambaforge/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/sgsdxzy/mambaforge/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2560, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
And it seems the output of `forward` is all `nan`. I cannot figure out why, help is needed.

Current state: apply `llama_multigpu` to a single gpu works correctly, but multiple gpus are still not working because of `nan`.

Resolves #135

### CODE REVIEW

**Comment by sgsdxzy** [comment]
This pr is fully functional and ready for merge.

Update:
1. Fixed the nan issue! It finally works! I don't know how to change triton device, is the current `with torch.cuda.device(input.device)` the proper way of doing it?
2. I think `llama_multigpu` is not necessary: accelerate can be used to dispatch the model between gpus with approptiate hooks, no need to manually do it. Reverted change to `llama.py`

**Comment by emvw7yf** [comment]
Thanks for your work on this! When trying to run 65b model on 2 GPUs using the following command:

```
CUDA_VISIBLE_DEVICES=0,1 python llama.py ./llama-65b c4 --wbits 4 --groupsize 128 --load llama-65b-4bit-128g.safetensors --benchmark 2048 --check
```

I'm still getting the following error, even with this patch.

```
Traceback (most recent call last):
  File "/home/code/projects/GPTQ-for-LLaMa/llama.py", line 468, in <module>
    benchmark(model, input_ids, check=args.check)
  File "/home/code/projects/GPTQ-for-LLaMa/llama.py", line 336, in benchmark
    out = model(
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/code/projects/GPTQ-for-LLaMa/llama.py", line 295, in forward
    tmp = self.module(*inp, **kwargs)
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/code/projects/GPTQ-for-LLaMa/quant.py", line 573, in forward
    query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin, position_ids)
  File "/home/code/projects/GPTQ-for-LLaMa/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 136, in apply_rotary_pos_emb
    cos = torch.gather(cos.repeat(gather_indices.shape[0], 1, 1, 1), 2, gather_indices)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA_gather)
```

**Comment by sgsdxzy** [comment]
@emvw7yf 
You would need something like
```
model = load_quant(args.model, args.load, args.wbits, args.groupsize)
max_memory = accelerate.utils.get_balanced_memory(model)
device_map = accelerate.infer_auto_device_map(model, max_memory=max_memory, no_split_module_classes=["LlamaDecoderLayer"])
print("Using the following device map for the quantized model:", device_map)
model = accelerate.dispatch_model(model, device_map=device_map, offload_buffers=True)
```
to dispatch the model correctly. The `llama_multigpu` is not working and I would like to keep this pr clean and minimal.

**Comment by sgsdxzy** [comment]
I still feel the speed is a bit lacking. 4bit on a single gpu is almost twice as fast as `LlamaForCausalLM.from_pretrained(model, load_in_8bit=True, llm_int8_threshold=0.0)`, but on a two-gpu setup (with nvlink) 4bit is only 15% faster than 8bit of `LLM.int8()`. Is my calling of triton kernel wasting communication here?

**Comment by emvw7yf** [comment]
@sgsdxzy it worked, thanks!

**Comment by GenTxt** [comment]
Glad to see emvw7yf has this working but it's not clear if it's the pull request or the extra coding snippet 'You would need something like ...'

Unfortunately I'm encountering the following errors using the original sgsdxzy/GPTQ-for-LLaMa/tree/fix_multigpu and current triton merge. System: ubuntu 22.04, python3.10, 2x RTX 24 gig cards, 64 gigs ram.

llama 30b triton 4bit model still loads on gpu 0 **only** while 65b 4bit goes OOM without any memory load on gpu 1 

CUDA_VISIBLE_DEVICES="0,1" python llama_inference.py models/llama-65b-4bit-128g --wbits 4 --text "It was a rainy day in Pizzaville when" --groupsize 128 --load models/llama-65b-4bit-128g/llama-65b-4bit-128g.safetensors --max_length 128 --min_length 32

Made changes to 'modelutils.py' and 'llama_inference.py'

DEV = torch.device('cuda:0')

to

DEV = torch.device('cuda')

Also edited and tested version of 'llama.py' based on above snippet (properly indented in script):

if args.load:
                  model = load_quant(args.model, args.load, args.wbits, args.groupsize)
                  max_memory = accelerate.utils.get_balanced_memory(model)
                  device_map = accelerate.infer_auto_device_map(model, max_memory=max_memory, no_split_module_classes=["LlamaDecoderLayer"])
                  print("Using the following device map for the quantized model:", device_map)
                  model = accelerate.dispatch_model(model, device_map=device_map, offload_buffers=True)
    else:
                  model = get_llama(args.model)
                  model.eval()

Assume this edit is not correct as single gpu 0 memory issues remain the same and the 'print' command fails.

Would appreciate a clear explanation on how to load both 30b and 65b models on 2 gpus for inference using current version of gptq triton.

Cheers,

**Comment by sgsdxzy** [comment]
@GenTxt What `accelerate` version are you using? and how can a `print` fail? What does it print?
You also need to remove any `model.to(something)`, if it is called the multi gpu load is ruined.
I am using https://github.com/oobabooga/text-generation-webui and after https://github.com/oobabooga/text-generation-webui/pull/1073 it should work transparently to load GPTQ triton in mutiple gpus.

ps: you can use three "\`" to indicate a block of code to pretty-format it. like
\```
code
\```
becomes
```
code
```

**Comment by GenTxt** [comment]
You're right. I should have mentioned that text-generation-webui is the only current way of loading 30b and 65b 4bit balanced on 2 gpus. 

https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/121

No issues, no OOM going back to the original pytorch/cuda models. (Just over a month ago? Geez)

What I was hoping for was to have the same multi-gpu option with 'llama_inference.py' as per my example above.

Unfortunately, that's still an issue but no big deal because webui saves the day.

Using accelerate 18.0 and triton 2.0.0

```
Cheers
```

**Pull request merged**
