### PR TITLE
style(project): format with yapf

### PR DESCRIPTION
**Pull request by tpoisonooo**
Just `yapf -i *.py  quant/*.py utils/*.py` to format python code.

### CODE REVIEW

**Comment by tpoisonooo** [comment]
@qwopqwop200  I just format the code, or owner does it by self.

**Comment by qwopqwop200** [comment]
Currently, this format change seems to break the readability of the code in some places.

**Comment by tpoisonooo** [comment]
> Currently, this format change seems to break the readability of the code in some places.

That is.. `yapf` has default format rules.  The default max `len(line)` is fixed, maybe 79.

Let's add a yapf config.  Please check [this](https://github.com/google/yapf#formatting-style) for more information.

**Comment by tpoisonooo** [comment]
About default 79, there is a RFC about ancient display (maybe 30 years ago) defined it.  

https://en.wikipedia.org/wiki/Characters_per_line

**Comment by tpoisonooo** [comment]
Added [.style.yapf](https://github.com/tpoisonooo/GPTQ-for-LLaMa/blob/format-with-yapf/.style.yapf),   expand `COLUMN_LIMIT` to 200 for large PC screen.

Check [this doc](https://pypi.org/project/yapf/#formatting-style)  to enable preferred style.  @qwopqwop200   ^_^

**Pull request merged**
